### ISSUE TITLE
PLEASE READ

### ISSUE THREAD

**Issue by ghost** [Bibhusan7/Random-password-generator#1]

**Comment by shikharadhikari** [comment]
I just saw your issue/comment in my gmail, even tho you have deleted it i could see it from gmail and dont say i copied your autoclicker cause thats the only easy way to make it for begineers and almost all youtubers have used the same code even tho I have published my autoclicker video before you.

**Comment by ghost** [comment]
> I just saw your issue/comment in my gmail, even tho you have deleted it i could see it from gmail and dont say i copied your autoclicker cause thats the only easy way to make it for begineers and almost all youtubers have used the same code even tho I have published my autoclicker video before you.

NO U DIDNT U MORON MY VIDEO IS POSTED FOR U USE UR EYES AND LOOK I MADE SURE OF IT.
